name: CI
on: [push, pull_request]
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [jammy, focal, bionic]
        compiler: [g++, clang++]

    container:
      image: ubuntu:${{matrix.version}}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc-multilib g++-multilib ninja-build cmake wget clang unzip file
          mkdir build

      - name: Configure
        # bionic cmake doesn't support the -B syntax for build dir
        working-directory: build
        # Replace with RelWithDebInfo when -O2 crash is fixed
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        working-directory: build
        run: ninja

      - name: Test
        run: |
          wget https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip
          unzip GC_WII_COMPILERS.zip
          MWCIncludes=. build/wibo GC/2.7/mwcceppc.exe -c test/test.c
          file test.o

      - name: Upload build
        uses: actions/upload-artifact@v2
        # Only upload build compiled against oldest glibc for compatibility
        if: matrix.compiler == 'bionic'
        with:
          name: wibo
          path: build/wibo

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: matrix.compiler == 'bionic' && startsWith(github.ref, 'refs/tags/')
        with:
          files: build/wibo
